/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hms;
import java.sql.*;
/**
 *
 * @author ezhilnero
 */
public class adddoc extends javax.swing.JFrame {
    
    int count=0;

        static Connection conn = null;
    Statement stmt = null;
    private static final String USERNAME = "root";
    private static final String PASSWORD = "";
    private static final String conn_str = "jdbc:mysql://localhost:3306/HMS";
    
    /**
     * Creates new form adddoc
     */
    public adddoc() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        dname_tf = new javax.swing.JTextField();
        salary_tf = new javax.swing.JTextField();
        did_tf = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        back_btn = new javax.swing.JButton();
        submit_btn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        dept_tf1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel2.setText("Doctor id :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(260, 260, 130, 30);

        jLabel3.setText("Name :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(260, 100, 130, 30);
        jPanel1.add(dname_tf);
        dname_tf.setBounds(380, 100, 110, 29);
        jPanel1.add(salary_tf);
        salary_tf.setBounds(380, 200, 110, 29);
        jPanel1.add(did_tf);
        did_tf.setBounds(380, 250, 130, 30);

        jLabel5.setText("salary :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(260, 200, 130, 30);

        back_btn.setText("Back");
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });
        jPanel1.add(back_btn);
        back_btn.setBounds(390, 300, 70, 31);

        submit_btn.setText("Submit");
        submit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit_btnActionPerformed(evt);
            }
        });
        jPanel1.add(submit_btn);
        submit_btn.setBounds(279, 300, 80, 31);

        jLabel6.setText("Dept :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(260, 150, 130, 30);
        jPanel1.add(dept_tf1);
        dept_tf1.setBounds(380, 150, 110, 29);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hms/doctor2.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 770, 440);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 763, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit_btnActionPerformed
        String pname ="DR."+dname_tf.getText().toUpperCase().toString();
        String dept =dept_tf1.getText().toUpperCase().toString();   
        int salary =Integer.parseInt(salary_tf.getText().toString());
       
       try{
      conn = DriverManager.getConnection(conn_str, USERNAME, PASSWORD);
            System.out.println("connected to DB");      
      stmt = conn.createStatement();
      String sql = "SELECT count(*) FROM doctor;";
      ResultSet rs = stmt.executeQuery(sql);
      while(rs.next()){
        count = rs.getInt("count(*)");
        System.out.println("count : "+count);
      }
      rs.close();
      count =count+1;
      sql = "INSERT INTO doctor(d_id,d_name,dept,allot,salary) VALUES ("+ count +",\""+pname+"\", \""+dept+"\", "+0+","+salary+");";
      stmt.executeUpdate(sql);
      System.out.println("Inserted records into the table...");
      did_tf.setText(String.valueOf(count));
      

   }catch(Exception se){
      //Handle errors for JDBC
      System.out.println("ERROR IS : " +se.toString());
   }        
// TODO add your handling code here:
    }//GEN-LAST:event_submit_btnActionPerformed

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
super.dispose();
new sys_adm_opt().setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_back_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adddoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adddoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adddoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adddoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adddoc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_btn;
    private javax.swing.JTextField dept_tf1;
    private javax.swing.JLabel did_tf;
    private javax.swing.JTextField dname_tf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField salary_tf;
    private javax.swing.JButton submit_btn;
    // End of variables declaration//GEN-END:variables
}
