/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hms;
import java.sql.*;
/**
 *
 * @author ezhilnero
 */
public class amb_recep extends javax.swing.JFrame {
    
    int a_no;
    
    static Connection conn = null;
    Statement stmt = null;
    private static final String USERNAME = "root";
    private static final String PASSWORD = "";
    private static final String conn_str = "jdbc:mysql://localhost:3306/HMS";

    /**
     * Creates new form amb_recep
     */
    public amb_recep() {
         initComponents();
        try{
      conn = DriverManager.getConnection(conn_str, USERNAME, PASSWORD);
      System.out.println("connected to DB");      
      stmt = conn.createStatement();
      String sql = "select amb_no from ambulance where avail = 1";
      ResultSet rs = stmt.executeQuery(sql);
      while(rs.next()){
        a_no = rs.getInt("amb_no");
        ambno_list.addItem(String.valueOf(a_no));
      }
      
      
      rs.close();
      conn.close();

   }catch(Exception se){
      //Handle errors for JDBC
      System.out.println("ERROR IS : " +se.toString());
   }
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        alert_btn = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        back_btn = new javax.swing.JButton();
        ambno_list = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Noto Serif CJK TC", 1, 13)); // NOI18N
        jLabel2.setText("Location :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(260, 160, 70, 19);

        jLabel3.setFont(new java.awt.Font("Noto Serif CJK TC", 1, 13)); // NOI18N
        jLabel3.setText("Cause :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(260, 200, 90, 19);

        jLabel4.setFont(new java.awt.Font("Noto Serif CJK TC", 1, 13)); // NOI18N
        jLabel4.setText("Amb no:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(260, 280, 90, 19);

        alert_btn.setText("Alert");
        alert_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alert_btnActionPerformed(evt);
            }
        });
        jPanel1.add(alert_btn);
        alert_btn.setBounds(290, 320, 90, 31);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(370, 200, 120, 29);
        jPanel1.add(jTextField2);
        jTextField2.setBounds(370, 240, 120, 29);
        jPanel1.add(jTextField3);
        jTextField3.setBounds(370, 160, 120, 29);

        back_btn.setText("Back");
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });
        jPanel1.add(back_btn);
        back_btn.setBounds(390, 320, 90, 31);

        jPanel1.add(ambno_list);
        ambno_list.setBounds(370, 280, 120, 29);

        jLabel5.setFont(new java.awt.Font("Noto Serif CJK TC", 1, 13)); // NOI18N
        jLabel5.setText("Casualities :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(260, 240, 90, 19);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hms/back8.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 775, 455);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 774, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 453, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        super.dispose();
        new receptionist().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_back_btnActionPerformed

    private void alert_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alert_btnActionPerformed
           System.out.println(ambno_list.getSelectedItem().toString());
        try{
      conn = DriverManager.getConnection(conn_str, USERNAME, PASSWORD);
      System.out.println("connected to DB");      
      stmt = conn.createStatement();
      String sql = "update ambulance set avail = 0 where amb_no = "+ambno_list.getSelectedItem().toString()+";";
      stmt.executeUpdate(sql);
      conn.close();

   }catch(Exception se){
      //Handle errors for JDBC
      System.out.println("ERROR IS : " +se.toString());
   }


        // TODO add your handling code here:
    }//GEN-LAST:event_alert_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(amb_recep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(amb_recep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(amb_recep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(amb_recep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new amb_recep().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alert_btn;
    private javax.swing.JComboBox<String> ambno_list;
    private javax.swing.JButton back_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
