/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hms;

/**
 *
 * @author ezhilnero
 */
public class doct_recp extends javax.swing.JFrame {

    /**
     * Creates new form doct_recp
     */
    public doct_recp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        d_no_tf = new javax.swing.JTextField();
        d_seacrch_btn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        d_name_tf = new javax.swing.JTextField();
        back_btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(770, 450));
        setResizable(false);

        jPanel1.setLayout(null);

        jLabel2.setText("  Doctor ID :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(243, 250, 100, 19);
        jPanel1.add(d_no_tf);
        d_no_tf.setBounds(350, 240, 160, 29);

        d_seacrch_btn.setText("Search");
        d_seacrch_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d_seacrch_btnActionPerformed(evt);
            }
        });
        jPanel1.add(d_seacrch_btn);
        d_seacrch_btn.setBounds(290, 310, 80, 31);

        jLabel3.setText("  Doctor name :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(240, 200, 110, 19);

        d_name_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d_name_tfActionPerformed(evt);
            }
        });
        jPanel1.add(d_name_tf);
        d_name_tf.setBounds(350, 190, 160, 29);

        back_btn.setText("Back");
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });
        jPanel1.add(back_btn);
        back_btn.setBounds(400, 310, 80, 31);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hms/back7.png"))); // NOI18N
        jLabel1.setToolTipText("");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 770, 450);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void d_name_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d_name_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_d_name_tfActionPerformed

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        super.dispose();
        new receptionist().setVisible(true);
    }//GEN-LAST:event_back_btnActionPerformed

    private void d_seacrch_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d_seacrch_btnActionPerformed
             
        if(!d_name_tf.getText().isEmpty()){
               super.dispose();
                new doctor_avail(d_name_tf.getText().toString().toUpperCase()).setVisible(true);
            }
            else if(!d_no_tf.getText().isEmpty()){
                super.dispose();
                new doctor_avail(Integer.parseInt(d_no_tf.getText().toString())).setVisible(true);
            }

    }//GEN-LAST:event_d_seacrch_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(doct_recp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(doct_recp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(doct_recp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(doct_recp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new doct_recp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_btn;
    private javax.swing.JTextField d_name_tf;
    private javax.swing.JTextField d_no_tf;
    private javax.swing.JButton d_seacrch_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
