/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hms;
import java.awt.Color;
import java.sql.*;
/**
 *
 * @author ezhilnero
 */
public class icu extends javax.swing.JFrame {
    int pno;
    int bedno,bedflag;
    String flag;
    
    static Connection conn = null;
    Statement stmt = null;
    private static final String USERNAME = "root";
    private static final String PASSWORD = "";
    private static final String conn_str = "jdbc:mysql://localhost:3306/HMS";

    /**
     * Creates new form icu
     */
    public icu() {
        initComponents();
        try{
      conn = DriverManager.getConnection(conn_str, USERNAME, PASSWORD);
      System.out.println("connected to DB");      
      stmt = conn.createStatement();
      String sql = "SELECT avail from icu where bed_no = 1;";
      ResultSet rs = stmt.executeQuery(sql);
      while(rs.next()){       
             if(rs.getInt("avail")==1)  
             {
                 bed_tf.addItem("1");
             }
      }
      sql = "SELECT avail from icu where bed_no = 2;";
      rs = stmt.executeQuery(sql);
      while(rs.next()){       
             if(rs.getInt("avail")==1)  
             {
                 bed_tf.addItem("2");
             }
      }
      sql = "SELECT avail from icu where bed_no = 3;";
      rs = stmt.executeQuery(sql);
      while(rs.next()){       
             if(rs.getInt("avail")==1)  
             {
                 bed_tf.addItem("3");
             }
      }
      sql = "SELECT avail from icu where bed_no = 4;";
      rs = stmt.executeQuery(sql);
      while(rs.next()){       
             if(rs.getInt("avail")==1)  
             {
                 bed_tf.addItem("4");
             }
      }
      sql = "SELECT avail from icu where bed_no = 5;";
      rs = stmt.executeQuery(sql);
      while(rs.next()){       
             if(rs.getInt("avail")==1)  
             {
                 bed_tf.addItem("5");
             }
      }
      sql = "SELECT avail from icu where bed_no = 6;";
      rs = stmt.executeQuery(sql);
      while(rs.next()){       
             if(rs.getInt("avail")==1)  
             {
                 bed_tf.addItem("6");
             }
      }
      sql = "SELECT avail from icu where bed_no = 7;";
      rs = stmt.executeQuery(sql);
      while(rs.next()){       
             if(rs.getInt("avail")==1)  
             {
                 bed_tf.addItem("7");
             }
      }
      sql = "SELECT avail from icu where bed_no = 8;";
      rs = stmt.executeQuery(sql);
      while(rs.next()){       
             if(rs.getInt("avail")==1)  
             {
                 bed_tf.addItem("8");
             }
      }
     
      rs.close();
      conn.close();

   }catch(Exception se){
      //Handle errors for JDBC
      System.out.println("ERROR IS : " +se.toString());
   }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pno_tf = new javax.swing.JTextField();
        bed_tf = new javax.swing.JComboBox<>();
        b4 = new javax.swing.JLabel();
        b7 = new javax.swing.JLabel();
        b2 = new javax.swing.JLabel();
        b5 = new javax.swing.JLabel();
        b8 = new javax.swing.JLabel();
        b3 = new javax.swing.JLabel();
        b6 = new javax.swing.JLabel();
        b1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        book_btn = new javax.swing.JButton();
        check_btn = new javax.swing.JButton();
        hint_tf = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Noto Serif CJK TC", 1, 16)); // NOI18N
        jLabel2.setText("Intensive Care Unit");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(160, 90, 160, 30);

        jLabel3.setText("pno :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(100, 140, 90, 19);

        jLabel5.setText("bed no :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(100, 180, 90, 19);

        pno_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pno_tfActionPerformed(evt);
            }
        });
        jPanel1.add(pno_tf);
        pno_tf.setBounds(190, 140, 90, 29);

        bed_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bed_tfActionPerformed(evt);
            }
        });
        jPanel1.add(bed_tf);
        bed_tf.setBounds(190, 180, 90, 29);

        b4.setFont(new java.awt.Font("Noto Serif CJK TC", 1, 16)); // NOI18N
        b4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b4.setText("B4");
        b4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.add(b4);
        b4.setBounds(550, 160, 40, 60);

        b7.setFont(new java.awt.Font("Noto Serif CJK TC", 1, 16)); // NOI18N
        b7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b7.setText("B7");
        b7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.add(b7);
        b7.setBounds(430, 340, 40, 60);

        b2.setFont(new java.awt.Font("Noto Serif CJK TC", 1, 16)); // NOI18N
        b2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b2.setText("B2");
        b2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.add(b2);
        b2.setBounds(550, 70, 40, 60);

        b5.setFont(new java.awt.Font("Noto Serif CJK TC", 1, 16)); // NOI18N
        b5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b5.setText("B5");
        b5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.add(b5);
        b5.setBounds(430, 250, 40, 60);

        b8.setFont(new java.awt.Font("Noto Serif CJK TC", 1, 16)); // NOI18N
        b8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b8.setText("B8");
        b8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.add(b8);
        b8.setBounds(550, 340, 40, 60);

        b3.setFont(new java.awt.Font("Noto Serif CJK TC", 1, 16)); // NOI18N
        b3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b3.setText("B3");
        b3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.add(b3);
        b3.setBounds(430, 160, 40, 60);

        b6.setFont(new java.awt.Font("Noto Serif CJK TC", 1, 16)); // NOI18N
        b6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b6.setText("B6");
        b6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.add(b6);
        b6.setBounds(550, 250, 40, 60);

        b1.setFont(new java.awt.Font("Noto Serif CJK TC", 1, 16)); // NOI18N
        b1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b1.setText("B1");
        b1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.add(b1);
        b1.setBounds(430, 70, 40, 60);

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(170, 290, 100, 40);

        book_btn.setText("Book");
        book_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                book_btnActionPerformed(evt);
            }
        });
        jPanel1.add(book_btn);
        book_btn.setBounds(170, 240, 100, 40);

        check_btn.setText("Check");
        check_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_btnActionPerformed(evt);
            }
        });
        jPanel1.add(check_btn);
        check_btn.setBounds(610, 370, 70, 30);

        hint_tf.setFont(new java.awt.Font("Noto Serif CJK TC", 3, 14)); // NOI18N
        hint_tf.setForeground(new java.awt.Color(255, 10, 0));
        jPanel1.add(hint_tf);
        hint_tf.setBounds(300, 140, 60, 30);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hms/icu.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 760, 440);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
super.dispose();
new other_opt().setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void check_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_btnActionPerformed
try{
      conn = DriverManager.getConnection(conn_str, USERNAME, PASSWORD);
      System.out.println("connected to DB");      
      stmt = conn.createStatement();
      String sql = "SELECT avail from icu where bed_no = 1;";
      ResultSet rs = stmt.executeQuery(sql);
      while(rs.next()){       
             if(rs.getInt("avail")==0)  
             {
                 b1.setForeground(Color.RED);
             }else{
b1.setForeground(Color.BLACK);
}
      }
      sql = "SELECT avail from icu where bed_no = 2;";
      rs = stmt.executeQuery(sql);
      while(rs.next()){       
             if(rs.getInt("avail")==0)  
             {
                 b2.setForeground(Color.RED);
             }else{
b2.setForeground(Color.BLACK);
}
      }
      sql = "SELECT avail from icu where bed_no = 3;";
      rs = stmt.executeQuery(sql);
      while(rs.next()){       
             if(rs.getInt("avail")==0)  
             {
                 b3.setForeground(Color.RED);
             }else{
b3.setForeground(Color.BLACK);
}
      }
      sql = "SELECT avail from icu where bed_no = 4;";
      rs = stmt.executeQuery(sql);
      while(rs.next()){       
             if(rs.getInt("avail")==0)  
             {
                 b4.setForeground(Color.RED);
             }else{
b4.setForeground(Color.BLACK);
}
      }
      sql = "SELECT avail from icu where bed_no = 5;";
      rs = stmt.executeQuery(sql);
      while(rs.next()){       
             if(rs.getInt("avail")==0)  
             {
                 b5.setForeground(Color.RED);
             }else{
b5.setForeground(Color.BLACK);
}
      }
      sql = "SELECT avail from icu where bed_no = 6;";
      rs = stmt.executeQuery(sql);
      while(rs.next()){       
             if(rs.getInt("avail")==0)  
             {
                 b6.setForeground(Color.RED);
             }else{
b6.setForeground(Color.BLACK);
}
      }
      sql = "SELECT avail from icu where bed_no = 7;";
      rs = stmt.executeQuery(sql);
      while(rs.next()){       
             if(rs.getInt("avail")==0)  
             {
                 b7.setForeground(Color.RED);
             }else{
b7.setForeground(Color.BLACK);
}
      }
      sql = "SELECT avail from icu where bed_no = 8;";
      rs = stmt.executeQuery(sql);
      while(rs.next()){       
             if(rs.getInt("avail")==0)  
             {
                 b8.setForeground(Color.RED);
             }else{
b8.setForeground(Color.BLACK);
}
      }
     
      rs.close();
      conn.close();

   }catch(Exception se){
      //Handle errors for JDBC
      System.out.println("ERROR IS : " +se.toString());
   }

        // TODO add your handling code here:
    }//GEN-LAST:event_check_btnActionPerformed

    private void book_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_book_btnActionPerformed
        pno =Integer.parseInt(pno_tf.getText().toString());
        bedno =Integer.parseInt(bed_tf.getSelectedItem().toString());
              
       
       try{
      conn = DriverManager.getConnection(conn_str, USERNAME, PASSWORD);
      System.out.println("connected to DB");      
      stmt = conn.createStatement();
      String sql = "SELECT ptype from Patients WHERE pid = "+pno+" ;";
      ResultSet rs = stmt.executeQuery(sql);
      while(rs.next()){
         flag = rs.getString("ptype");
      }
      sql = "SELECT bedno from Patients WHERE pid = "+pno+" ;";
      rs = stmt.executeQuery(sql);
      while(rs.next()){
         bedflag = rs.getInt("bedno");
      }
      if(bedflag>0)
      {
        sql = "UPDATE icu SET avail = 1  WHERE bed_no = "+bedflag+" ;";
        stmt.executeUpdate(sql);
        sql = "UPDATE icu SET pno = null  WHERE bed_no = "+bedflag+" ;";
        stmt.executeUpdate(sql);
      }
      if(flag.equals("out"))
      {
          hint_tf.setText("*error");
      }else{
      sql = "UPDATE icu SET avail = 0  WHERE bed_no = "+bedno+" ;";
      stmt.executeUpdate(sql);
      sql = "UPDATE icu SET pno = "+ pno +" WHERE bed_no = "+bedno+" ;";
      stmt.executeUpdate(sql);
      sql = "UPDATE Patients SET bedno ="+bedno+" WHERE pid = "+pno+" ;";
      stmt.executeUpdate(sql);
      System.out.println("update success");
      }

      
      

   }catch(Exception se){
      //Handle errors for JDBC
      System.out.println("ERROR IS : " +se.toString());
   }


        // TODO add your handling code here:
    }//GEN-LAST:event_book_btnActionPerformed

    private void bed_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bed_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bed_tfActionPerformed

    private void pno_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pno_tfActionPerformed
      // TODO add your handling code here:
    }//GEN-LAST:event_pno_tfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(icu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(icu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(icu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(icu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new icu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel b1;
    private javax.swing.JLabel b2;
    private javax.swing.JLabel b3;
    private javax.swing.JLabel b4;
    private javax.swing.JLabel b5;
    private javax.swing.JLabel b6;
    private javax.swing.JLabel b7;
    private javax.swing.JLabel b8;
    private javax.swing.JComboBox<String> bed_tf;
    private javax.swing.JButton book_btn;
    private javax.swing.JButton check_btn;
    private javax.swing.JLabel hint_tf;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField pno_tf;
    // End of variables declaration//GEN-END:variables
}
