/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hms;
import static hms.patients_recep.conn;
import java.sql.*;

/**
 *
 * @author ezhilnero
 */
public class lab_apply extends javax.swing.JFrame {
    int pid,count,amount;
    String test;
    
    static Connection conn = null;
    Statement stmt = null;
    private static final String USERNAME = "root";
    private static final String PASSWORD = "";
    private static final String conn_str = "jdbc:mysql://localhost:3306/HMS";

    /**
     * Creates new form lab_apply
     */
    public lab_apply() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        pno_tf = new javax.swing.JTextField();
        rno_tf = new javax.swing.JLabel();
        amnt_tf = new javax.swing.JLabel();
        test_tf = new javax.swing.JComboBox<>();
        back_btn = new javax.swing.JButton();
        submit_btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Noto Serif CJK TC", 3, 20)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("APPLY FOR TEST");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(150, 80, 250, 40);

        jLabel3.setFont(new java.awt.Font("Noto Serif CJK TC", 3, 16)); // NOI18N
        jLabel3.setText("Test :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(210, 200, 100, 24);

        jLabel4.setFont(new java.awt.Font("Noto Serif CJK TC", 3, 16)); // NOI18N
        jLabel4.setText("Amount :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(210, 250, 100, 24);

        jLabel5.setFont(new java.awt.Font("Noto Serif CJK TC", 3, 16)); // NOI18N
        jLabel5.setText("Receipt no :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(210, 300, 110, 24);

        jLabel6.setFont(new java.awt.Font("Noto Serif CJK TC", 3, 16)); // NOI18N
        jLabel6.setText("P no :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(210, 150, 90, 24);
        jPanel1.add(pno_tf);
        pno_tf.setBounds(360, 150, 150, 29);
        jPanel1.add(rno_tf);
        rno_tf.setBounds(360, 300, 130, 30);
        jPanel1.add(amnt_tf);
        amnt_tf.setBounds(360, 250, 130, 30);

        test_tf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CANCER", "CT", "DENGUE", "HIV", "JAUNDICE", "MRI", "TB", "X-RAY", "MALARIA" }));
        jPanel1.add(test_tf);
        test_tf.setBounds(360, 200, 150, 29);

        back_btn.setText("Back");
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });
        jPanel1.add(back_btn);
        back_btn.setBounds(390, 360, 140, 31);

        submit_btn.setText("Submit");
        submit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit_btnActionPerformed(evt);
            }
        });
        jPanel1.add(submit_btn);
        submit_btn.setBounds(220, 360, 130, 31);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hms/plain3.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 770, 450);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 766, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed

super.dispose();
new lab_opt().setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_back_btnActionPerformed

    private void submit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit_btnActionPerformed
        pid = Integer.parseInt(pno_tf.getText().toString());
        test = test_tf.getSelectedItem().toString().toUpperCase();
        try{
      conn = DriverManager.getConnection(conn_str, USERNAME, PASSWORD);
            System.out.println("connected to DB");      
      stmt = conn.createStatement();
      String sql = "SELECT amount FROM tests where t_name = \""+test+"\"";
      ResultSet rs = stmt.executeQuery(sql);
      while(rs.next()){
        amount=rs.getInt("amount");
        amnt_tf.setText(String.valueOf(amount));
      } 
      sql = "SELECT count(*) FROM lab;";
      rs = stmt.executeQuery(sql);
      while(rs.next()){
        count = rs.getInt("count(*)");
      } 
      rs.close();
      count=count+1;
      rno_tf.setText(String.valueOf(count));
      sql = "INSERT INTO lab (rno,pno,test,amount) VALUES ("+ count +","+pid+", \""+test+"\", "+amount+");";
      stmt.executeUpdate(sql);
      System.out.println("Inserted records into the table...");
      

   }catch(Exception se){
      //Handle errors for JDBC
      System.out.println("ERROR IS : " +se.toString());
   }




    }//GEN-LAST:event_submit_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(lab_apply.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(lab_apply.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(lab_apply.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(lab_apply.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new lab_apply().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amnt_tf;
    private javax.swing.JButton back_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField pno_tf;
    private javax.swing.JLabel rno_tf;
    private javax.swing.JButton submit_btn;
    private javax.swing.JComboBox<String> test_tf;
    // End of variables declaration//GEN-END:variables
}
