/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hms;


import java.sql.*;

/**
 *
 * @author ezhilnero
 */
public class patient_depadm extends javax.swing.JFrame {
    static Connection conn = null;
    Statement stmt = null;
    private static final String USERNAME = "root";
    private static final String PASSWORD = "";
    private static final String conn_str = "jdbc:mysql://localhost:3306/HMS";
    
    String name;
    String disorder;
    String type;
    long phno;
    String gender;
    int did;
    String dname;
    String slot;
    

    /**
     * Creates new form patient_depadm
     */
    public patient_depadm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pid_tf = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        disorder_tf = new javax.swing.JLabel();
        type_tf = new javax.swing.JLabel();
        phno_tf = new javax.swing.JLabel();
        gender_tf = new javax.swing.JLabel();
        dname_tf = new javax.swing.JLabel();
        name_tf = new javax.swing.JLabel();
        slot_tf = new javax.swing.JLabel();
        did_tf = new javax.swing.JLabel();
        back_btn = new javax.swing.JButton();
        search_btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(null);

        pid_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pid_tfActionPerformed(evt);
            }
        });
        jPanel1.add(pid_tf);
        pid_tf.setBounds(250, 60, 140, 29);

        jLabel2.setText("disorder :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(120, 140, 120, 30);

        jLabel3.setText("type :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(120, 170, 120, 30);

        jLabel4.setText("ph no :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(120, 200, 120, 30);

        jLabel5.setText("gender :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(120, 230, 120, 30);

        jLabel6.setText("doc name :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(120, 290, 120, 30);

        jLabel7.setText("name :");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(120, 110, 120, 30);

        jLabel8.setText("slot :");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(120, 320, 120, 30);

        jLabel9.setText("doc no :");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(120, 260, 120, 30);
        jPanel1.add(disorder_tf);
        disorder_tf.setBounds(250, 140, 120, 30);
        jPanel1.add(type_tf);
        type_tf.setBounds(250, 170, 120, 30);
        jPanel1.add(phno_tf);
        phno_tf.setBounds(250, 200, 120, 30);
        jPanel1.add(gender_tf);
        gender_tf.setBounds(250, 230, 120, 30);
        jPanel1.add(dname_tf);
        dname_tf.setBounds(250, 290, 120, 30);
        jPanel1.add(name_tf);
        name_tf.setBounds(250, 110, 120, 30);
        jPanel1.add(slot_tf);
        slot_tf.setBounds(250, 320, 120, 30);
        jPanel1.add(did_tf);
        did_tf.setBounds(250, 260, 120, 30);

        back_btn.setText("Back");
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });
        jPanel1.add(back_btn);
        back_btn.setBounds(590, 340, 100, 31);

        search_btn.setText("search");
        search_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_btnActionPerformed(evt);
            }
        });
        jPanel1.add(search_btn);
        search_btn.setBounds(430, 60, 110, 31);

        jLabel1.setIcon(new javax.swing.ImageIcon("/home/ezhilnero/Pictures/netbeans/patient.png")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 770, 440);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 767, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pid_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pid_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pid_tfActionPerformed

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
super.dispose();
new dept_admin().setVisible(true);
        
// TODO add your handling code here:
    }//GEN-LAST:event_back_btnActionPerformed

    private void search_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_btnActionPerformed
try{
      conn = DriverManager.getConnection(conn_str, USERNAME, PASSWORD);
      System.out.println("connected to DB");      
      stmt = conn.createStatement();
      String sql = "SELECT pid,pname,pdisorder,ptype,ppno,gender,d_no,slot FROM Patients where pid ="+pid_tf.getText().toString()+";";
      ResultSet rs = stmt.executeQuery(sql);
      while(rs.next()){
        name = rs.getString("pname");
        disorder = rs.getString("pdisorder");
        type= rs.getString("ptype");
        phno= rs.getLong("ppno");
        gender= rs.getString("gender");
        did= rs.getInt("d_no");
        slot= rs.getString("slot");
      }
       sql = "SELECT d_name FROM doctor where d_id ="+did+";";
       rs = stmt.executeQuery(sql);
      while(rs.next()){
        dname = rs.getString("d_name");
      }
      name_tf.setText(name.toUpperCase());
      disorder_tf.setText(disorder.toUpperCase());
      type_tf.setText(type.toUpperCase());
      phno_tf.setText(String.valueOf(phno).toUpperCase());
      gender_tf.setText(gender.toUpperCase());
      did_tf.setText(String.valueOf(did).toUpperCase());
      dname_tf.setText(dname.toUpperCase());
      slot_tf.setText(slot.toUpperCase());
      
      rs.close();
      conn.close();

   }catch(Exception se){
      //Handle errors for JDBC
      System.out.println("ERROR IS : " +se.toString());
   }        // TODO add your handling code here:
    }//GEN-LAST:event_search_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(patient_depadm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(patient_depadm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(patient_depadm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(patient_depadm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new patient_depadm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_btn;
    private javax.swing.JLabel did_tf;
    private javax.swing.JLabel disorder_tf;
    private javax.swing.JLabel dname_tf;
    private javax.swing.JLabel gender_tf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel name_tf;
    private javax.swing.JLabel phno_tf;
    private javax.swing.JTextField pid_tf;
    private javax.swing.JButton search_btn;
    private javax.swing.JLabel slot_tf;
    private javax.swing.JLabel type_tf;
    // End of variables declaration//GEN-END:variables
}
