/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hms;

import java.sql.*;

/**
 *
 * @author ezhilnero
 */
public class patients_recep extends javax.swing.JFrame {
    //copy this
    static Connection conn = null;
    Statement stmt = null;
    private static final String USERNAME = "root";
    private static final String PASSWORD = "";
    private static final String conn_str = "jdbc:mysql://localhost:3306/HMS";
    String pdisorder;
    
    int count;
    /**
     * Creates new form patients_recep
     */
    public patients_recep() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Back = new javax.swing.JButton();
        ppno_tf = new javax.swing.JTextField();
        pdisorder_tf = new javax.swing.JTextField();
        pname_tf = new javax.swing.JTextField();
        p_type_tf = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        p_gender_tf = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        pid_tf = new javax.swing.JLabel();
        doc_btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel2.setText("Number :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(190, 170, 70, 19);

        jLabel3.setText("Disorder :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(190, 210, 80, 19);

        jLabel4.setText("Gender :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(190, 250, 70, 19);

        jLabel5.setText("Name :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(190, 130, 70, 19);

        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        jPanel1.add(Back);
        Back.setBounds(340, 360, 100, 31);
        jPanel1.add(ppno_tf);
        ppno_tf.setBounds(310, 170, 240, 29);
        jPanel1.add(pdisorder_tf);
        pdisorder_tf.setBounds(310, 210, 240, 29);
        jPanel1.add(pname_tf);
        pname_tf.setBounds(310, 130, 240, 29);

        p_type_tf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "OUT", "IN" }));
        jPanel1.add(p_type_tf);
        p_type_tf.setBounds(310, 290, 150, 29);

        jButton2.setText("Submit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(210, 360, 100, 31);

        jLabel6.setText("type :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(190, 290, 90, 19);

        p_gender_tf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        jPanel1.add(p_gender_tf);
        p_gender_tf.setBounds(310, 250, 150, 29);

        jLabel7.setText("pid :");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(190, 330, 80, 19);
        jPanel1.add(pid_tf);
        pid_tf.setBounds(310, 330, 160, 20);

        doc_btn.setText("see doctor");
        doc_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doc_btnActionPerformed(evt);
            }
        });
        jPanel1.add(doc_btn);
        doc_btn.setBounds(470, 360, 110, 31);

        jLabel1.setIcon(new javax.swing.ImageIcon("/home/ezhilnero/Pictures/netbeans/back6.png")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 770, 450);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        super.dispose();
        new receptionist().setVisible(true);
    }//GEN-LAST:event_BackActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String pname =pname_tf.getText().toLowerCase().toString();
        String ppno =ppno_tf.getText().toLowerCase().toString();
        pdisorder =pdisorder_tf.getText().toLowerCase().toString();
        String pgender =p_gender_tf.getSelectedItem().toString().toLowerCase();
        String ptype =p_type_tf.getSelectedItem().toString().toLowerCase();      
       
       try{
      conn = DriverManager.getConnection(conn_str, USERNAME, PASSWORD);
            System.out.println("connected to DB");      
      stmt = conn.createStatement();
      String sql = "SELECT count(*) FROM Patients;";
      ResultSet rs = stmt.executeQuery(sql);
      while(rs.next()){
        count = rs.getInt("count(*)");
        System.out.println("count : "+count);
      }
      rs.close();
      count =count++;
      sql = "INSERT INTO Patients(pid,pname,pdisorder,ptype,ppno,gender) VALUES ("+ count +",\""+pname+"\", \""+pdisorder+"\", \""+ptype+"\", \""+ppno+"\", \""+pgender+"\");";
      stmt.executeUpdate(sql);
      System.out.println("Inserted records into the table...");
      pid_tf.setText(String.valueOf(count));
      

   }catch(Exception se){
      //Handle errors for JDBC
      System.out.println("ERROR IS : " +se.toString());
   }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void doc_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doc_btnActionPerformed
        super.dispose();
      new doct_dep_details(pdisorder).setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_doc_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    //copy this
        try{
            
        }catch(Exception e){
            System.out.println("ERROR IS: "+e.toString());
        }
        //to this
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(patients_recep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(patients_recep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(patients_recep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(patients_recep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new patients_recep().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton doc_btn;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> p_gender_tf;
    private javax.swing.JComboBox<String> p_type_tf;
    private javax.swing.JTextField pdisorder_tf;
    private javax.swing.JLabel pid_tf;
    private javax.swing.JTextField pname_tf;
    private javax.swing.JTextField ppno_tf;
    // End of variables declaration//GEN-END:variables
}
